<?php

namespace AppBundle\Repository;

/**
 * adressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adressRepository extends \Doctrine\ORM\EntityRepository
{
}
