<?php

namespace AppBundle\Repository;

/**
 * basketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class basketRepository extends \Doctrine\ORM\EntityRepository
{

}
