<?php

namespace AppBundle\Repository;

/**
 * cardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cardRepository extends \Doctrine\ORM\EntityRepository
{
}
