<?php

namespace AppBundle\Repository;

/**
 * CatToProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatToProductRepository extends \Doctrine\ORM\EntityRepository
{
}
