<?php

namespace AppBundle\Repository;

/**
 * imageProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageProductRepository extends \Doctrine\ORM\EntityRepository
{
}
