<?php

namespace AppBundle\Repository;

/**
 * produitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productsRepository extends \Doctrine\ORM\EntityRepository
{
}
