<?php

namespace AppBundle\Repository;

/**
 * ProductToBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductToBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
