<?php

namespace AppBundle\Repository;

/**
 * quantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quantityRepository extends \Doctrine\ORM\EntityRepository
{
}
