<?php

namespace AppBundle\Repository;

/**
 * salesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class salesRepository extends \Doctrine\ORM\EntityRepository
{
}
